# -*- coding: utf-8 -*-
"""cazzeggio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TlNnvpJmewdOjsDVo7de4gTPRa7X-0AF
"""

##variabili

nome_ia = "CASPER"
argomenti = ("come va?" , "di che vuoi parlare?" , "che tempo fa?" , "un calcolo", "quanti giorni ha questo mese?" , "fammi un alberello" ,  "ciao amore" , "esci")
<<<<<<< HEAD
risposte_utente = []
=======

>>>>>>> c70f965f85e6b30319ca5fba12e7cfdf42fef18e



##funzioni

<<<<<<< HEAD
def chiedi():
  risposta = input()
  risposte_utente.append(risposta)
  return risposta

def stampa(risposta):
  print(risposta)
=======
>>>>>>> c70f965f85e6b30319ca5fba12e7cfdf42fef18e

def opzioni(argomenti):
    for i, argomento in enumerate(argomenti):
        print("-" , i, argomento)



##programma

print ("Ciao, mi chiamo", nome_ia)
print ("Come ti chiami?")
<<<<<<< HEAD
nome_utente= chiedi()
=======
nome_utente = input()
>>>>>>> c70f965f85e6b30319ca5fba12e7cfdf42fef18e

def sesso_utente(nome):
  if nome_utente [-1] == "a" or "e":
    print("Benvenuta " + nome_utente)
  else:
    print("Benvenuto " + nome_utente)

sesso_utente(nome_utente)

while True:
  print("\nCosa facciamo?")
  opzioni(argomenti)
<<<<<<< HEAD
  argomento = chiedi()
=======
  argomento = input()
>>>>>>> c70f965f85e6b30319ca5fba12e7cfdf42fef18e




  if argomento == "come va?":
    print("sto lavorando.... dimmi")

  if argomento == "di che vuoi parlare?":
    print("vuoi che racconto una barzelletta?")
<<<<<<< HEAD
    risposta_barzelletta = chiedi()
=======
    risposta_barzelletta = input()
>>>>>>> c70f965f85e6b30319ca5fba12e7cfdf42fef18e
    if risposta_barzelletta == "si":
      print("il colmo per chip? abbaiare...")

#matematica

  if "+" in argomento:
    numeri = argomento.split("+")
    risultato = float(numeri[0]) + float(numeri[1])
    print("sommando" , argomento , "otteniamo:")
    print(risultato)
  if "-" in argomento:
    numeri = argomento.split("-")
    risultato = float(numeri[0]) - float(numeri[1])
    print("sottraendo" , argomento , "otteniamo:")
    print(risultato)
  if "/" in argomento:
    numeri = argomento.split("/")
    risultato = float(numeri[0]) / float(numeri[1])
    print("dividendo" , argomento , "otteniamo:")
    print(risultato)
  if "*" in argomento:
    numeri = argomento.split("*")
    risultato = float(numeri[0]) * float(numeri[1])
    print("moltiplicando" , argomento , "otteniamo:")
    print(risultato)

  if argomento == "che tempo fa?":
    print("connessione ai server meteo in corso...")

#giorni in mese

  if argomento == "quanti giorni ha questo mese?":
    print("dimmi di che mese parli")
<<<<<<< HEAD
    mese = chiedi()
=======
    mese = input()
>>>>>>> c70f965f85e6b30319ca5fba12e7cfdf42fef18e

    anno = 0

    if mese == "febbraio":
      print("di che anno parliamo?")
<<<<<<< HEAD
      anno = int(chiedi())
=======
      anno = int(input())
>>>>>>> c70f965f85e6b30319ca5fba12e7cfdf42fef18e
    def durata_mese (mese , anno):
      if mese == "febbraio":
        if anno % 4 == 0:
          return 29
        return 28
      if mese == "aprile" or mese == "giugno" or mese == "settembre" or mese == "novembre":
        return 30
      if mese == "gennaio" or mese == "marzo" or mese == "maggio" or mese == "luglio" or mese == "agosto" or mese == "ottobre" or mese == "dicembre":
        return 31
      else:
        return "che mese è?"
    print(mese , "contiene " ,  (durata_mese(mese , anno)) , "giorni")

  if argomento == "fammi un alberello":
    def alberello (n):
      i = 0
      while i <= n:
        i += 1
        print("*" * i)

    alberello(15)

  if argomento == "esci":
    print("a presto!")
<<<<<<< HEAD
    print(risposte_utente)
=======
>>>>>>> c70f965f85e6b30319ca5fba12e7cfdf42fef18e
    break

  if argomento == "ciao amore":
    amore_mio = 0
    while amore_mio < 10:
      print("AMORE MIO")
      amore_mio = amore_mio + 1
    print("e ancora e ancora e ancora")

  else:
    print(" ")

